
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Forward Docker daemon port for external Docker client connection
  config.vm.network "forwarded_port", guest: 2375, host: 2375, host_ip: "127.0.0.1"

  config.vm.network "private_network", type: "dhcp"

  config.vm.network "forwarded_port", guest: 443, host: 443
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  config.vm.network "forwarded_port", guest: 8082, host: 8082

  # Define a synced folder for Vagrant
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__auto: true, rsync__exclude: [".git/"]

  # Provision the VM with Docker
 config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y docker.io docker-compose
  SHELL

  # for start 
  #config.vm.provision "shell", inline: <<-SHELL
  #  cd /vagrant
  #  docker-compose up -d
  #SHELL

  #  need to restart the VM after provisioning
 config.vm.provision "shell", inline: "shutdown -r now", run: "always"

end
